### ISSUE TITLE
interpret results

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#6]
We need to look at the two tables and the figure and tell a consistent story about the differences/similarities between them.
@DVMath and @fccoelho  are invited to give their pitacos as well.

**Comment by fccoelho** [comment]
In the figure, the prior and posterior curves for the Hierarchical prior extend beyond 1. WTF!?!

**Comment by maxbiostat** [comment]
This is R's weird way of plotting things. I noticed this, tried to fix it,
to no avail.
Will think of a solution, but no promises made.

On 13 February 2015 at 11:47, Flávio Codeço Coelho <notifications@github.com
> wrote:

> In the figure, the prior and posterior curves for the Hierarchical prior
> extend beyond 1. WTF!?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxbiostat/opinion_pooling/issues/6#issuecomment-74242358>
> .
>



-- 
Luiz Max Fagundes de Carvalho
PhD student, Institute of Evolutionary Biology,  School of Biological
Sciences,
Ashworth Laboratories, Ash 2, office 123
University of Edinburgh, United Kingdom.
http://br.linkedin.com/pub/luiz-max-carvalho/49/687/283

**Comment by DVMath** [comment]
What is the final message?  I wrote that results can vary from discarding some of the opinions to even assigning equal weights.  Anything else?

**Comment by maxbiostat** [comment]
Good question. Maybe theres little posterior sensitivity because ME and MKL
choose distributions with ranges that encompass the others.
Just guessing for now

**Comment by fccoelho** [comment]
I think that (one of) the final message(s) is that each method seem to serve a slightly different purpose, ME seem good to select the least informative opinion, while KL seem to be giving higher weights to extreme opinions in order to position the pooled dist. in the middle of all (do you agree wiith this view?) 

To make a long story short, the take home message is that there is not one best way to chose weights, but the methods should be select in the light of the desired results. So, even though we retain some subjectivity in the process, by using the proposed methods we have a rational and reproducible for chosing \alpha_i.

**Comment by DVMath** [comment]
I think that ME is the method that takes to the most extreme opinions,
whereas KL is in the middle.

--
Daniel A. M. Villela
